descriptor-schema-version: "2.2"

info:
  name: Gateway_Agent
  description: "Gateway-as-a-Service agent application. Monitors southbound controllers and publishes data to the cloud"
  version: "2.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  cpuarch: "x86_64"  
  type: docker

  resources:
    profile: c1.small

    network:
      -
        interface-name: eth0
        ports:
            tcp: [9000]

    devices:
      -
        type: serial
        label: HOST_DEV1
        usage: App monitors Weather and Location

# Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["python", "/usr/bin/main.py"] 
